l_french:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 PRODUCTION_MATERIALS_ALUMINIUM: "Aluminium"
 PRODUCTION_VEHICLES_BUTTON: "Construire des blindés"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "Les blindés n'ont §Rpas encore été inventés§!!"
 PRODUCTION_ARMOR_FILTER: "Blindés"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "§HProduction sous licence§! : $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§HProduction des usines sous licence§!\nTotal : $VALUE|+%$\nDégradation :"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§YDifférence technologique de la licence§! :\n Base : $BASE|+%$\n Total modifié : $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§YModificateur de licence§!:\n Base : $BASE|+%$\n Total modifié : $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§YPas dans la même faction que le concédeur de licence§! : $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§YActuellement aucune licence§! : $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST: "§YCoût de la licence§! : $AMOUNT|Y$ £civ_factory "
